name: Generate Progress Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests matplotlib

      - name: Run progress chart script
        env:
          # The GitHub token is provided automatically by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The repository owner and name are also available as built-in variables
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python generate_progress_chart.py
      
      - name: Update README cache busting query
        run: |
          DATE=$(date +%Y%m%d%H%M%S)
          sed -i "s/progress_chart\.png?v=[0-9]*/progress_chart.png?v=$DATE/" README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Update learning progress chart"
          file_pattern: 'README.md progress_chart.png'
          commit_options: '--no-verify'

